# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\MongoService:
        arguments:
            $mongoUri: '%env(MONGO_URI)%'
            $mongoDB:  '%env(MONGO_DB)%'

    App\Service\DeliveryService:
        arguments:
            $orsApiKey: '%env(ORS_API_KEY)%'

    App\Controller\UploadController:
        arguments:
            $uploadDir: '%kernel.project_dir%/public/images'


    App\Service\MailerService:
        arguments:
            $from: '%env(MAILER_SENDER_EMAIL)%'
            $fromName: '%env(MAILER_SENDER_NAME)%'

    app.jwt_cookie_extractor:
        class: App\Security\JwtCookieExtractor
        tags:
            - { name: lexik_jwt_authentication.token_extractor }
